src/clifford_systems/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('employee/',include('employee.urls'), name="Employee Index"),
    # re_path(r'^', include('employee.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header="Clifford Systems Administration"
admin.site.site_title="Clifford Systems Administration"
admin.site.index_title="Welcome to Clifford Systems Administration Site"

src/main/urls.py
from django.urls import path, re_path
from . import views
from database import views as database_views


urlpatterns = [
    # employee endpoints
    path('employee/', views.employee_home, name="Employee Index"),
    path('employee/login', views.login_employee, name="Employee Login"),
    path('employee/create', views.create_employee, name="Create Employee"),
    path('employee/profile', views.profile_employee, name="Employee Logout"),
    path('employee/products', views.products_employee, name="Employee Products"),
    path('employee/products/create', views.products_employee_create, name="Employee Products Create"),
    path('employee/clients', views.clients_employee, name="Client List"),
    path('employee/clients/create', views.clients_employee_create, name="Client Create"),
    path('employee/orders', views.orders_employee, name="Order List"),
    path('employee/factory', views.factory_employee, name="Factory List"),
    path('employee/magazine', views.magazine_employee, name="Magazine List"),
    path('employee/', views.employee_home, name="Employee Index"),


    path('login',views.login_user, name="Login"),
    # client endpoints
    path('',views.index, name="Home Page"),
    path('profile', views.profile_user, name="Profile"),
    path('products/<int:id>', views.products_user, name="Products"),

    path('logout', views.logout, name="Logout"),
    

    # api endpoints
    path('api/user', database_views.user_list, name="User List"),
    path('api/user/<int:pk>', database_views.user_list, name="User Detail"),
    path('api/products', database_views.product_list, name="Product List"),
    path('api/products/<int:pk>', database_views.product_list, name="Product Detail"),
    path('api/clients', database_views.client_list, name="Client List"),
    path('api/clients/<int:pk>', database_views.client_list, name="Client Detail"),
]

src/database/models.py
from urllib import request
from djongo import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class UserManager(BaseUserManager):
    def create_employee(self, email, name, phone, password , **extra_fields):
        """Creates and saves a new user"""
        if not email:
            raise ValueError('Users must have an email address')
        if not name:
            raise ValueError('Users must have a name')
        # if not username:
        #     raise ValueError('Users must have a username')

        extra_fields.setdefault('is_employee', True)
            
        user = self.model(
            email=self.normalize_email(email),
            name = name,
            phone = phone,
            is_employee = True,
            **extra_fields
            )
        user.set_password(password)
        user.save()

        return user

    def create_client(self, email, name, password , **extra_fields):    
        """Creates and saves a new user"""
        if not email:
            raise ValueError('Users must have an email address')
        if not name:
            raise ValueError('Users must have a name')
        # if not username:
        #     raise ValueError('Users must have a username')
        
        user = self.model(
            email=self.normalize_email(email),
            name = name,
            is_client = True,
            **extra_fields
            )
        user.set_password(password)
        user.save()

        return user


    def create_user(self, email, name, password, **extra_fields):
        """Creates and saves a new user"""
        if not email:
            raise ValueError('Users must have an email address')
        if not name:
            raise ValueError('Users must have a name')
        # if not username:
        #     raise ValueError('Users must have a username')
        
        user = self.model(
            email=self.normalize_email(email),
            name = name,
            **extra_fields
            )
        user.set_password(password)
        user.save()

        return user


    def create_superuser(self, email,name, password, **extra_fields):

        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)


        """Creates and saves a new superuser"""
        user = self.create_user(email, name, password, **extra_fields)
        user.is_staff = True
        user.is_superuser = True
        user.save()

        return user



class custom_User(AbstractBaseUser, PermissionsMixin):
    # roles
    is_employee = models.BooleanField(default=False)
    is_client = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    
    # entry data
    email = models.EmailField(unique=True)
    # username = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name',]

    def __str__(self):
        return self.name



# class Admin(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)

#     email = models.EmailField()
#     username = models.CharField(max_length=50)
#     password = models.CharField(max_length=50)

#     def __str__(self):
#         return self.username


# class Employees(models.Model):
#     # needed to create user model
#     user = models.OneToOneField(User, on_delete=models.CASCADE)

#     name = models.CharField(max_length=50) # name of the employee
#     email = models.EmailField()
#     phone = models.CharField(max_length=15) # phone number of the employee
#     # authentication
#     username = models.CharField(max_length=50) 
#     password = models.CharField(max_length=50)

#     def __str__(self):
#         return self.name


# class Customers(models.Model):
#     # needed to create user model
#     user = models.OneToOneField(User, on_delete=models.CASCADE)

#     c_id = models.AutoField(primary_key=True) # unique id for each customer
#     name = models.CharField(max_length=50) # name of the distributor company
#     email = models.EmailField() # email of the distributor company
#     address = models.CharField(max_length=100) # address of the customer
#     phone = models.CharField(max_length=15) # phone number of the customer
#     cart = models.ArrayReferenceField(to='Orders',) # array of cart objects
#     # authentication
#     username = models.CharField(max_length=50) 
#     password = models.CharField(max_length=50)

#     def __str__(self):
#         return self.name



class Products(models.Model):
    product_id = models.AutoField(primary_key=True) # id for a product
    title = models.CharField(max_length=100) # title to show 
    description = models.TextField() # description that shows under title
    price = models.IntegerField() # price for this product
    image = models.ImageField(null=True, blank=True, upload_to='images/') # images
    box_quantity = models.IntegerField() # number of items in the box
    box_weight = models.IntegerField() # weight of the box in grams
    box_dimensions = models.CharField(max_length=100,default="-") # dimensions of the box
    stock = models.IntegerField(default=0) # number of items in stock

    def __str__(self):
        return self.title

class Production(models.Model):
    pass
    # date = models.DateField() # date of the production
    # quantity = models.IntegerField() # quantity of the product produced


# create a cart class to hold a single data for the actual cart
class Cart(models.Model):
    product_id = models.IntegerField() # id for a product (refrences to the product)
    quantity = models.IntegerField() # quantity of the product in the cart
    price = models.DecimalField(max_digits=10, decimal_places=2) # price of the product in the cart

    class Meta:
        abstract = True


# orders will have this structure
# this will also be used to create temporary carts with the DRAFTED option
# if user logins and has a DRAFTED order, it will be loaded by default into the cart
class Orders(models.Model):
    ACCEPTEDED = 'AC'
    PENDING = 'PE'
    CANCELLED = 'CA'
    DRAFTED = 'DR'

    customer_id = models.IntegerField() # customer who placed the order
    employee_id = models.IntegerField() # employee who processed the order
    date = models.DateField(auto_now=True) # date of the order
    state = models.CharField(max_length=2, 
        choices=[
            (ACCEPTEDED, 'Accepted'),
            (PENDING, 'Pending'),
            (CANCELLED, 'Cancelled'),
            (DRAFTED, 'Drafted')
            ]) # state of the order
    cart = models.ArrayField(model_container=Cart) # array of products in the order
    total = models.CharField(max_length=20) # total price of the order

    def __str__(self):
        return self.cart

src/main/models.py
from django.db import models

src/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model, authenticate, login

from database.models import Products

class EmployeeCreateForm(UserCreationForm):
    
    email = forms.EmailField(max_length=100, required=True, label='Email')
    name = forms.CharField(max_length=100, required=True, label='Name')
    # username = forms.CharField(max_length=100, required=True, label='Username')
    phone = forms.CharField(max_length=100, required=True, label='Phone')

    class Meta:
        model = get_user_model()
        fields = ('name','email','phone','password1','password2')

    def save(self, commit=True):    
        user = super().save(commit=False)
        user.is_employee = True

        if commit:
            user.save()
        return user

class EmployeeLoginForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True, label='Email')
    password = forms.CharField(widget=forms.PasswordInput, required=True, label='Password')

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError('Wrong email or password')
            if not user.check_password(password):
                raise forms.ValidationError('Wrong email or password')
        return super(EmployeeLoginForm, self).clean(*args, **kwargs)

class LoginForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True, label='Email')
    password = forms.CharField(widget=forms.PasswordInput)


    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)

            if not user:
                raise forms.ValidationError('User does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Password is incorrect')

        return super(LoginForm, self).clean(*args, **kwargs)

class ClientCreateForm(UserCreationForm):
        
        email = forms.EmailField(max_length=100, required=True, label='Email')
        name = forms.CharField(max_length=100, required=True, label='Name')
        # username = forms.CharField(max_length=100, required=True, label='Username')
        phone = forms.CharField(max_length=100, required=True, label='Phone')
        address = forms.CharField(max_length=100, required=False, label='Address')


        class Meta:
            model = get_user_model()
            fields = ('name','email','phone','address','password1','password2')
    
        def save(self, commit=True):    
            user = super().save(commit=False)
            user.is_client = True
    
            if commit:
                user.save()
            return user

class ClientLoginForm(forms.Form):
    email = forms.EmailField(max_length=100, required=True, label='Email')
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            user = authenticate(email=email, password=password)

            if not user:
                raise forms.ValidationError('User does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Password is incorrect')

        return super(ClientLoginForm, self).clean(*args, **kwargs)


class AddProductForm(forms.ModelForm):
    title = forms.CharField(max_length=100, required=True, label='Title')
    description = forms.CharField(max_length=100, label='Description')
    price = forms.IntegerField(required=True, label='Price')
    box_quantity = forms.IntegerField(required=True, label='Box Quantity')
    box_weight = forms.IntegerField(required=True, label='Box Weight')
    box_dimensions = forms.CharField(max_length=100, label='Box Dimensions')
    stock = forms.IntegerField( label='Current Stock')

    class Meta:
        model = Products
        fields = ('title','description','price','image','box_quantity','box_weight','box_dimensions','stock')


    def save(self, commit=True):
        product = super().save(commit=False)
        if commit:
            product.save()
        return product


# class EmployeeSignUpForm(UserCreationForm):
#     name = forms.CharField(max_length=50, required=True, label='Full Name')
#     email = forms.EmailField(required=True, label="Email")
#     phone = forms.CharField(max_length=15, required=True, label="Phone Number")

#     class Meta:
#         model = Employees
#         fields = ['name','email','phone','username', 'password1', 'password2']
    
#     def save(self, commit=True):
#         user = super(EmployeeSignUpForm, self).save(commit=False)
#         user.is_employee = True
#         if commit:
#             user.save()
#         return user

src/main/templates/employee/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Boostrap4 link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block title %}
    <title>Employee</title>
    {% endblock %}
</head>
<body>

    
    {% block content %}
    {% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

src/main/templates/employee/clients.html
{% extends 'client/base.html' %}

{% block title %}
<title>Clients</title>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>
                <h1>Clients
                <a href="/employee/clients/create" class="btn btn-primary">New Client</a>

                </h1>
            </p>
            </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Address</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>random name</td>
                        <td>email@test.com</td>
                        <td>+3558231039</td>
                        <td>Rruga e Durrsit</td>
                        <td>
                            <a href="#" class="btn btn-primary">Edit</a>
                            <a href="#" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                    {% for client in clients %}
                    <tr>
                        <td>{{ client.name }}</td>
                        <td>{{ client.email }}</td>
                        <td>{{ client.phone }}</td>
                        <td>{{ client.address }}</td>
                        <td>
                            <a href="/employee/clients/{{ client.id }}/edit" class="btn btn-primary">Edit</a>
                            <a href="/employee/clients/{{ client.id }}/delete" class="btn btn-danger">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                   
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        
    </div>
</div>
{% endblock %}

src/main/templates/employee/clients_create.html
{% extends 'client/base.html' %}


{% load crispy_forms_tags %}


{% block title %}
<title>Create Client</title>
{% endblock %}

{% block content %}
<div class="container">
    {% if msg %}
    <div class="alert alert-success">
        {{ msg }}
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-12">
            <h1>Create Client</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

src/main/templates/employee/factory.html
{% extends 'client/base.html' %}

<div class="row">
    <div class="col-3">
       <div class="list-group" id="list-tab" role="tablist">
           <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Clients</a>
           <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Register</a>
           <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Daily Production</a>
           <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Supply Order</a>
           <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">View Supply Stock</a>
           <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">View Product Stock</a>
           
       </div>
    </div>
</div>

src/main/templates/employee/index.html
{% extends 'client/base.html' %}

{% load static %}

{% block title %}
<title>Employee Index</title>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-3">
       <div class="list-group" id="list-tab" role="tablist">
           <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Clients</a>
           <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Register</a>
           <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Daily Production</a>
           <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Supply Order</a>
           <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">View Supply Stock</a>
           <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">View Product Stock</a>
           
       </div>
    </div>

    <div class="col-9">
        <div class="row">
        <div class="col-lg-4 ">
            <a href="/employee/clients">
            <div class="card" style="width: 20rem;">
                <button class="btn btn-default">
              <img class="card-img-top" src="{% static 'clients.png' %}" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title text-primary">Clients</h5>
              </div>
                </button>
            </div>
        </a>
          </div>


          <div class="col-lg-4 ">
            <a href="/employee/clients/create">
            <div class="card" style="width: 20rem;">
                <button class="btn btn-default">
              <img class="card-img-top" src="{% static 'register.png' %} "  alt="Card image cap" style="{width:30%}">
              <div class="card-body">
                <h5 class="card-title text-primary">Register Clients</h5>
              </div>
            </button>
            </div>
            </a>
          </div>

          <div class="col-lg-4 ">
            <a href="/employee/orders">
            <div class="card" style="width: 20rem;">
                <button class="btn btn-default">
              <img class="card-img-top" src="{% static 'transaction icone.png' %}" alt="Card image cap" style="{width:30%}">
              <div class="card-body">
                <h5 class="card-title text-primary">Transactions</h5>
              </div>
            </button>
            </div>
            </a>
            <br>
          </div>
           

          
          <div class="col-lg-4 ">
            <a href="/employee/factory">
            <div class="card" style="width: 20rem;">
                <button class="btn btn-default">
              <img class="card-img-top" src="{% static 'Production.png' %}" alt="Card image cap" style="{width:30%}">
              <div class="card-body">
                <h5 class="card-title text-primary">Input Daily Production</h5>
              </div>
            </button>
            </div>
            </a>
          </div>
          
          <div class="col-lg-4 ">
            <a href="/employee/orders">
            <div class="card" style="width: 20rem;">
                <button class="btn btn-default">
              <img class="card-img-top" src="{% static 'Supplypng.png' %}" alt="Card image cap" style="{width:30%}">
              <div class="card-body">
                <h5 class="card-title text-primary">Order Supplys</h5>

              </div>
            </button>
            </div>
            </a>
          </div>

          <div class="col-lg-4 ">
            <a href="/employee/magazine">
            <div class="card" style="width: 20rem;">
                <button class="btn btn-default">
              <img class="card-img-top" src="{% static 'warehouse (2).png' %}" alt="Card image cap" style="{width:30%}">
              <div class="card-body">
                <h5 class="card-title text-primary" >View Supply Stock</h5>
              </div>
            </button>
            </div>
            </a>
          </div>
        </div>

       </div>
     </div>

</div>

{% endblock %}

src/main/templates/employee/login.html
{% extends 'client/base.html' %}


{% load crispy_forms_tags %}


{% block title %}

<title>Employee Login</title>
{% endblock %}


{% block content %}
    <center>

        <div class="row ">
            <div class="col-md-12">
                <p class="display-3">Log In</p>
                <p>You will be redirected to your respecive page</p>
            </div>
        </div>
        <form method="post" class="form-group">
          {% csrf_token %}
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                  <div class="card shadow-2-strong" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
                      <table class="table">
                        {{form|crispy}}
                      </table>
                      <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
          
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </form>
    </center>
    
{% endblock %}

src/main/templates/employee/magazine.html
{% extends 'client/base.html' %}

src/main/templates/employee/orders.html
{% extends 'client/base.html' %}

<div class="row">
    <div class="col-3">
       <div class="list-group" id="list-tab" role="tablist">
           <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Clients</a>
           <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Register</a>
           <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Daily Production</a>
           <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">Supply Order</a>
           <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">View Supply Stock</a>
           <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">View Product Stock</a>
           
       </div>
    </div>
</div>

src/main/templates/employee/products_create.html
{% extends 'client/base.html' %}


{% block title %}
<title>Create Product</title>
{% endblock %}

{% load crispy_forms_tags %}

    
{% block content %}
  {% if msg %}
    <div class="alert alert-success">
        {{ msg }}
    </div>
  {% endif %}
<center>

    <div class="row ">
        <div class="col-md-12">
            <p class="display-3">Create New Product</p>
        </div>
    </div>
    <form method="POST" class="form-group" action="" enctype="multipart/form-data">
       {% csrf_token %}
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
              <div class="card shadow-2-strong" style="border-radius: 1rem;">
                <div class="card-body p-5 text-center">
                  <table class="table">
                        {{form|crispy}}
                  </table>
                  <button class="btn btn-primary btn-lg btn-block" id="submit">Create</button>
      
                </div>
              </div>
            </div>
          </div>
        </div>
    </form>
</center>
<script>

  title = document.querySelector('#id_title');
  description = document.querySelector('#id_description');
  price = document.querySelector('#id_price');
  image = document.querySelector('#id_image');
  box_quantity = document.querySelector('#id_box_quantity');
  box_weight = document.querySelector('#id_box_weight');
  box_dimensions = document.querySelector('#id_box_dimensions');
  stock = document.querySelector('#id_stock');
  submit = document.querySelector('#submit');

  submit.addEventListener('click', function(e){
    if(title.value == '' || description.value == '' || price.value == '' || image.value == '' || box_quantity.value == '' || box_weight.value == '' || box_dimensions.value == ''){
      e.preventDefault();
      alert('Please fill out all fields');
    }
    else{
      var formdata = new FormData();
      formdata.append("title", title.value);
      formdata.append("description", description.value);
      formdata.append("price", price.value);
      formdata.append("image", image.files[0]);
      formdata.append("box_quantity", box_quantity.value);
      formdata.append("box_weight", box_weight.value);
      formdata.append("box_dimensions", box_dimensions.value);
      formdata.append("stock", stock.value);

      var requestOptions = {
        method: 'POST',
        body: formdata,
        headers: {
         'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
        }
      };

      fetch("http://127.0.0.1:8000/api/products", requestOptions)
        .then(res => alert(res.json().message))
    }
  });

</script>

{% endblock %}

src/main/templates/employee/register.html
{% extends 'employee/base.html' %}


{% load crispy_forms_tags %}

{% comment %} add a title in middle of screen {% endcomment %}


{% block title %}
<title>Employee Registration</title>
{% endblock %}

<div class="d-flex justify-center-center">
    <p class="display-4">Employee Registration</p>
</div>


{% block content %}

    {% comment %} make the form in middle of the screen {% endcomment %}


    <div class="container">
        <div class="row">
            <div class="col-md-offset-3 col-md-5">
                <form action="#" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">Register</button>
                </form>
            </div>
        </div>
{% endblock %}